/*
 * DcMotor_Private.h
 *
 Author: BAYOUMII
 */

#ifndef HAL_DCMOTOR_DRIVER_DCMOTOR_PRIVATE_H_
#define HAL_DCMOTOR_DRIVER_DCMOTOR_PRIVATE_H_


#endif /* HAL_DCMOTOR_DRIVER_DCMOTOR_PRIVATE_H_ */
